name: csf-biomarker-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - statsmodels
  - scikit-learn
  - matplotlib
  - seaborn
  - pip
  - pip:
      - geoparse
      - shap
      - adjustText
