name: ad_csf_bioinfo
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - matplotlib
  - seaborn
  - scanpy
  - r-base=4.3
  - r-seurat
  - bioconductor-mast
  - bioconductor-fgsea
